### ISSUE TITLE
SQL gen count_encounter count_patient should have analogs for FHIR core table refs 

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#100]
`from cumulus_library.schema import counts`

CURRENT

**count_patient**
count(distinct subject_ref) as cnt

**count_encounter**
count(distinct encounter_ref) as cnt

DESIRED

**count_document**
count(distinct document_ref) as cnt

**count_condition**
count(distinct condition_ref) as cnt

**count_observation**
count(distinct observation_ref) as cnt

Note: there are few common CORE tables, therefore this list should not grow uncontrolled.

**Comment by comorbidity** [comment]
NOTICE: by default, the **cnt_patient** should be >= 10, as that is generally referenced in HIPAA as the small bin size. 
Hospitals should be allowed to override this default, for example in small sample size studies where the study case definition yields small numbers of patients.

**Comment by dogversioning** [comment]
> NOTICE: by default, the **cnt_patient** should be >= 10, as that is generally referenced in HIPAA as the small bin size. Hospitals should be allowed to override this default, for example in small sample size studies where the study case definition yields small numbers of patients.

Getting wrappers for all the main core tables is pretty close to next on my list - just wanted to get the cleanup done first.

**Comment by dogversioning** [comment]
But, relatedly -  size 10 is the current default if you elect to use `get_where_clauses`:

```    def get_where_clauses(
        self, clause: Union[list, str, None] = None, min_subject: int = 10
    ) -> str:
        """convenience method for constructing where clauses"""
        if clause is None:
            return [f"cnt_subject >= {min_subject}"]
        elif isinstance(clause, str):
            return [clause]
        elif isinstance(clause, list):
            return clause
        else:
            raise CountsBuilderError(f"get_where_clauses invalid clause {clause}")```
I'll get the downstream studies wired up to use this function more aggresively.
