### ISSUE TITLE
ICD10 "section" code should be available for ICD10 conditions.

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#117]
The Section code is the part before the "." in an ICD10 code, it is three characters. 
Example: I10 is the "section" code for Hypertension, and there are more specific codes underneath this section. 

https://www.icd10data.com/ICD10CM/Codes/I00-I99/I10-I16/I10-/I10

**Comment by dogversioning** [comment]
Closing this - this should move to a view in the UMLS study, moving this issue to there for consideration
