### ISSUE TITLE
CodeSystems in CORE should use UMLS abbreviations when provided

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#128]
CodeSystems in CORE should use abbreviation when producing CSV files easier to read and much less junk in files.
Abbreviations are from UMLS
https://github.com/smart-on-fhir/cumulus-library/blob/main/cumulus_library/schema/typesystem.py#L32

**Comment by dogversioning** [comment]
given this conflict this has with the us core profile support, i'm going to close this for now as a won't do, but we can reopen in the future, or otherwise rework as part of refactoring the existing typesystem code.
