### ISSUE TITLE
Consider renaming all the `_code_system` aliases to just `_system`

### ISSUE THREAD

**Issue by mikix** [smart-on-fhir/cumulus-library#211]
When we did the big field rename for 2.0 that aligned us closer to the FHIR spec, we used the following scheme for codeable fields:

```
    interpretation_code,
    interpretation_code_system,
    interpretation_display,
```

But I personally find that a little confusing in a world where we are mostly mapping the FHIR spec. Why not use just `system`, which is what the field is called. `code_system` makes _my_ brain think we're talking about `code.system` instead of `system`.

So my pitch is that for 3.0, we consider a mass rename back like `s/code_system/system/g` as one of its breaking changes.

**Comment by dogversioning** [comment]
For postertity, documenting our off-thread discussion:
- We are going to continue using `code_system` for new tables in 2.0, and then make the change in 3.0
- For studies we control, we should consistently use the pattern `baseResource_code_system` when joining into tables so it will be easier to bulk replace going forward.
