### ISSUE TITLE
Consider removing non-profile fields from vital signs table

### ISSUE THREAD

**Issue by mikix** [smart-on-fhir/cumulus-library#212]
The `core__observation_vital_signs` table has `valueCodeableConcept_*` and `interpretation_*` fields that aren't used in the US Core profile.

valueCodeableConcept is easy - Vital Signs use valueQuantity instead. None of the vital signs profiles use a codeable concept value.

interpretation is a little trickier. I suppose it's still valid. It's just not a must-support part of the profile, so maybe we should cut it from this profile-oriented table. The data is still in `core__observation`.

**Comment by mikix** [comment]
Hmm, Andy says that interpretation is useful, and Jamie says that component.valueCodeableConcept is used in genomics and "any qualifier values" which give an example of mentioning body site where a temperature was taken.

So maybe my examples in the description should be ignored and the table is fine actually.

Will let Matt decide whether to close this ticket or leave it open as a reminder to just do a general sweep of these tables for 3.0.

**Comment by dogversioning** [comment]
i think i'm going to close this one in favor of a more holistic 'handling the fields beyond the core profile' research spike (#216) rather than scope it just to this one table.
