### ISSUE TITLE
enhanced support for us core Patient extensions

### ISSUE THREAD

**Issue by James-R-Jones** [smart-on-fhir/cumulus-library#22]
On cumulus_library/studies/core/patient.sql, would be great to review with our Cerner data and support the different US Core extensions.

Specifically, suggest exposing counts of the OMB race CATEGORY and OMB ethnicity CATEGORY separately, rather than our previous "patient-reported" one. Should also test to confirm having both of these populated (potentially with cardinality >1 on race) does not introduce overcounting in `core__count_patient`.

While we're here, suggest exposing the (display) values in https://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-sex.htm, https://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-birthsex.html, and https://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-genderIdentity.html if present, noting that genderIdentity may appear multiple times.

**Comment by James-R-Jones** [comment]
Double counting due to race and ethnicity extensions seems fixed now!

Do we see any of the other extensions? [http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex](http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-birthsex.html) at least should be required and may differ from gender

**Comment by dogversioning** [comment]
I think now that we're comfortable with this approach we can do the same for all the extensions present on the patient resource?

**Comment by James-R-Jones** [comment]
Worth a shot to see what's being populated

**Comment by dogversioning** [comment]
@James-R-Jones ok, swinging back around on this - i'm not seeing any extensions for `sex`, `birthsex`, or `genderIdentity` in what we're getting back from cerner currently.

That makes me inclined to close this issue or mark it in some way that we know it's not on our end - any thoughts?

**Comment by James-R-Jones** [comment]
race and ethnicity are coming through perfectly now, we can close this and I'll follow up with some somewhat suggested edits to the docs as part of a larger process
