### ISSUE TITLE
Research spike: testing athena queries

### ISSUE THREAD

**Issue by dogversioning** [smart-on-fhir/cumulus-library#26]
Right now, queries are being validated in two ways:

- Linting for syntax errors by SQLFluff
- Manual testing during development

While better than nothing, having a true unit or integration test config would be ideal - we'd also love for something to be free. Things we have looked at so far:

- Moto support for athena is a WIP - notably, many things assume you're using the default profile, which breaks in our case - and it does not, and will not, support a SQL execution engine - you just tell it what responses to provide, which is more centered on lambda testing.
- Localstack purports to have a presto/hive instance with a mock AWS API for athena, but this is gated behind a license. We briefly looked into this at the start but there is some configuration burden to overcome.

So, this ticket should address the following questions:
- Should we purchase a localstack license for this?
- Since we're not worried about performance testing, can we use a simpler presto/[insert db] configuration with synthea data to validate if queries are running as expected?
- Could we get "close enough" by testing these in something like postgres directly?
- Is there another alternative we're missing?

The output of this spike is a recommendation for a technical approach.

**Comment by mikix** [comment]
Some examples of errors that our solution would ideally be able to catch:
- Referencing non-existent tables, which a simple syntax fluff check doesn't check (i.e. SQL that errors out on run)
- Duplicate rows, which are easy to slip in if we aren't careful as we flatten and join tables (i.e. logic errors)

Both of those would likely want us to be passing our code through a real SQL engine for integration testing.
