### ISSUE TITLE
DocRef table QA

### ISSUE THREAD

**Issue by James-R-Jones** [smart-on-fhir/cumulus-library#34]
two small issues
1. We are seeing duplication where there is a loinc code and another code in doc_type_display. Doesn't affect overall counts but makes looking at the code for the note confusing.
2. Might be good to use the text as a fallback if doc_type_display is unknown. Possible freetext phi spot if not previously philtered though, so be careful.

Of note, this code to pull date from the linked encounter date appears to be working.

**Comment by dogversioning** [comment]
this should be handled by coding refactors and the `cumulus__none` handler.
