### ISSUE TITLE
Core Encounter timing out in Athena

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#38]
Workaround: use a table instead of view, drop postalcode which isn't in use. 

`drop table core__count_encounter_month;

create table core__count_encounter_month as
with powerset as
(
    select distinct
          count(distinct P.subject_id) as cnt_subject,
          count(distinct E.encounter_id) as cnt_encounter
        , enc_class.code as enc_class_code
        , start_month
        , age_at_visit
        , P.gender
        , P.race_display
    from core__encounter E, core__patient P
    where E.subject_ref = P.subject_ref
    group by CUBE (enc_class, start_month, age_at_visit, gender, race_display)
)
select  distinct cnt_encounter as cnt
        , enc_class_code, start_month
        , age_at_visit, gender, race_display
from    powerset
where    cnt_subject >= 10
order by start_month asc, enc_class_code, age_at_visit asc
;`

**Comment by comorbidity** [comment]
first reported by Regenstrief (david)

**Comment by dogversioning** [comment]
Resolved via #50
