### ISSUE TITLE
FHIR Procedure is needed for exclusion criteria of procedure/encounter

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#41]
For example, Hypertension (and will be other study types) we need Procedure.

**Comment by mikix** [comment]
The ETL supports procedures these days! :tada:  So the library is unblocked from adding its own support, and I'll unassign myself.

**Comment by comorbidity** [comment]
Procedure **performeddatetime** is not always actual dates, can be partial like 
**2015-10**
