### ISSUE TITLE
Implement VSAC Downloader using UMLS API Key

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#42]
Input: 
* UMLS APIKey
* OID (object id) or URL pointing to the valueset

Output: 
* JSON of FHIR ValueSet
https://www.hl7.org/fhir/valueset.html

Note: the ValueSet may be a "grouping", such that recursive fetching is needed to get nested ValuSets. 
Example: https://cts.nlm.nih.gov/fhir/res/ValueSet/2.16.840.1.113883.3.3616.200.110.102.7001

**Comment by comorbidity** [comment]
if only OID is provided and not a URL, build a URL like 
`url = f"https://cts.nlm.nih.gov/fhir/res/ValueSet/{oid_object_identifier}"`

**Comment by comorbidity** [comment]
Priority: not urgent, workaround is to do this by hand manually as a human being (which @comorbidity is already doing)

**Comment by dogversioning** [comment]
Addressed via #223
