### ISSUE TITLE
core__count_condition_icd10_month empty when using SNOMED-CT instead of ICD10

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#51]
suggested fix (either A or B ) 

(A) remove requirement that FHIR Condition.code is ICD system. 
Make this an optional join, allowing the hospital asserted EHR codeable concept "system, code, display" remain intact without any modification. 

(B) create new view **core__count_condition_month** that does not join **core__join_condition_icd**

**Comment by comorbidity** [comment]
from @James-R-Jones 

Not totally unexpected per http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-condition.html#mandatory-and-must-support-data-elements SNOMED CT (or translations to it) is req for problem list entries

**Comment by dogversioning** [comment]
We don't have a SNOMED vocab table, but if we did, we could come up with something to handle this case.

**Comment by dogversioning** [comment]
resolved via #60
