### ISSUE TITLE
Library should support FHIR Condition in either SNOMED or ICD based system

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#52]
This is the larger scope of the issue discovered around `cumulus-library` requiring ICD based code system. 
 https://github.com/smart-on-fhir/cumulus-library/issues/51

NOTE: library often assumes a single code system which could create issues in the future
`condition.coding[1].code`

Example 
SELECT DISTINCT
    c.subject_ref,
    c.encounter_ref,
    c.cond_code.coding[1].code AS cond_code, -- noqa: LT01,RF02
    c.recorded_week AS cond_week,
    s.enc_class_code,
    s.age_at_visit,
    s.ed_note,
    s.variant_era
FROM core__condition AS c,
    covid_symptom__study_period AS s,
WHERE
    c.cond_code.coding[1].code = define_dx.code -- noqa: LT01,RF02
    AND c.encounter_ref = s.encounter_ref;

**Comment by dogversioning** [comment]
Resolved via #60
