### ISSUE TITLE
"with VS for condition" FHIR Condition category should specify "encounter" vs "problem-list"

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#55]
https://build.fhir.org/valueset-condition-category.html

applies to counts, especially 
**core__count_condition_icd10_month**

requested by @James-R-Jones

**Comment by comorbidity** [comment]
Related to "Encounter Reason" https://github.com/smart-on-fhir/cumulus-library/issues/31

**Comment by comorbidity** [comment]
Resolved: `core__count_condition_month`.**cond_category_code**

Note that core__count_condition_icd10_month no longer exists.

**Comment by dogversioning** [comment]
@comorbidity should we remove prior icd10_month datasets from the aggregator?
