### ISSUE TITLE
Minor: Vocab.ICD10 should be called ICD10CM to distinguish between CM=diagnosis and PCS=procedure

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#64]
related to PCS 
https://github.com/smart-on-fhir/cumulus-library/issues/41
https://github.com/smart-on-fhir/cumulus-library-hypertension/issues/10

cumulus_library/schema/typesystem.py

class Vocab(FHIR):
    """
    Terminologies (mapped to UMLS) referenced by Cumulus
    https://terminology.hl7.org/
    """

    ICD9 = "http://hl7.org/fhir/sid/icd-9-cm"
    ICD10 = "http://hl7.org/fhir/sid/icd-10-cm"
    LOINC = "http://loinc.org"
    SNOMED = "http://snomed.info/sct"
    UMLS = "http://www.nlm.nih.gov/research/umls/"
    RXNORM = "http://www.nlm.nih.gov/research/umls/rxnorm"
    CPT = "http://www.ama-assn.org/go/cpt"

**Comment by dogversioning** [comment]
Obseleted by the umls study
