### ISSUE TITLE
minor: FHIR Code "system" is a reserved keyword in SQL

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#65]
But "system" is allowed word in Athena/Presto so we haven't yet had an issue. 

options 
* do nothing until it becomes a problem for a non Athena/Presto location 
* use quotes everywhere like "system" 
* name instead "code_system" everywhere

**Comment by dogversioning** [comment]
@comorbidity Since we are making a breaking change with the 1.0 release, we should consider deciding on what do to with this now.

**Comment by dogversioning** [comment]
@comorbidity so based on what we just decided for the condition table, and allowing for other cases where we may have a table with more than one codeable concept, I'm now pretty strongly coming down on the side of `code_system` being the right name.

**Comment by dogversioning** [comment]
@comorbidity Per the above PR, I'm about to close this issue out, with the following guidance for the core tables:
- if a system is present, it should be labeled as code_system as a column name
- the exception: if you are joining a code from another table, or are joining multiple codes, you can give each a semantic prefix related to a FHIR resource, i.e. enc_system, cond_system, etc.

This will only be enforced for core tables, though I'd suggest we adopt it as a general rubric, for readability reasons.
