### ISSUE TITLE
Suggestion: Encounter.class.display will be more useful than code

### ISSUE THREAD

**Issue by James-R-Jones** [smart-on-fhir/cumulus-library#66]
Epic uses an internal code system for encounter.class that has numbers as codes.

Suggest updating cumulus_library/studies/core/encounter.sql to use `display` rather than `code` on line 52

**Comment by comorbidity** [comment]
Related to additional Encounter elements #31
https://github.com/smart-on-fhir/cumulus-library/issues/31

**Comment by comorbidity** [comment]
![image](https://github.com/smart-on-fhir/cumulus-library/assets/96439283/5774d247-f367-41ab-9b84-a767cc671e64)
