### ISSUE TITLE
CORE MedicationRequest: provide simple access to "Category" and "Encounter"

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#67]
https://github.com/smart-on-fhir/cumulus-library/blob/main/cumulus_library/studies/core/medication_request.sql

https://hl7.org/fhir/medicationrequest-definitions.html#MedicationRequest.category
https://hl7.org/fhir/medicationrequest-definitions.html#MedicationRequest.encounter

**Comment by comorbidity** [comment]
https://hl7.org/fhir/medicationrequest-definitions.html#MedicationRequest.category

select distinct cat_coding.code as category_code
from 
core__medicationrequest mr, 
unnest(mr.category) AS t (mr_cat), 
unnest(mr_cat.coding) AS t (cat_coding)
limit 50

**Comment by comorbidity** [comment]
also Status Reason 
https://hl7.org/fhir/valueset-medicationrequest-status-reason.html

**Comment by dogversioning** [comment]
this is handled by the flattening table work done in #166
