### ISSUE TITLE
SOE "Sequence of events" table needed for linking resources to FHIR Encounter

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#74]
EPIC Condition.encounter is OPTIONAL
UCDavis screenshare is true, this would be a curveball. Likely means I will update CORE to find “encounter.diagnosis” and/or “condition.encounter”
http://hl7.org/fhir/r4/condition-definitions.html#Condition.encounter
https://build.fhir.org/encounter-definitions.html#Encounter.diagnosis

@dogversioning noted this is true in FHIR spec as well.

**Comment by comorbidity** [comment]
CORE linking of **encounter_ref** and **subject_ref** is a 🛑 blocker for progress on many/most things
Applies to
FHR Condition 13% of Cerner 
FHIR Medication (Cerner rare, Epic common)
FHIR Observation (Cerner rare )

Likely will invoke building the common “SOE” (Sequence of events) table in health studies
Condition.recordeddate is between Encounter.period.start and Encounter.period.end
MedicationRequest.authoredOn is between Encounter.period.start and Encounter.period.end

**Comment by comorbidity** [comment]
COUNT report for each FHIR resource type having or lacking linkages in SOE

**Comment by dogversioning** [comment]
resolved via #85
