### ISSUE TITLE
Multiple Race is confusing "White American Indian or Alaska Native"

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#78]
If this is supposed to be "White" AND "American Indian or Alaska Native", then there should be a separator between the labels like "[White][American Indian or Alaska Native]"

**Comment by dogversioning** [comment]
So we need an example of a dataset containing more than one code per patient before we can do any design work here. we haven't found this in either the cerner data or synthea data. But right now, this field is an array, per patient, of every code available from the dataset. If this was present, it would look like this: "[White,American Indian or Alaska Native]"

**Comment by comorbidity** [comment]
UCDavis is where I saw this happen (Epic EHR)

**Comment by dogversioning** [comment]
i don't know if they're comfortable with this, but i'd love to see the post-ETL json/have them run a specific query against the etl patient table for something with multiple race extensions and send us a data sample.
