### ISSUE TITLE
Process Request: Explainable query logic for dashboard users

### ISSUE THREAD

**Issue by James-R-Jones** [smart-on-fhir/cumulus-library#80]
Where this already exists I can stub it into the dashboards, but we need a way to educate dashboard users (public health analysts) on the logic used in our queries so they can trust/understand how to interpret all of the columns in the counts tables.

Pointing to US Core FHIR profile data elements and HL7/ONC/etc value sets gets us pretty far. But where those values are not directly present in the data, getting over the last mile of "what am I looking at and how was it determined?" still needs some work.

I see 2 opportunities here to create HIGH ADDITIONAL VALUE:
1. We can add a freetext description of what each query is counting to its description blurb. THERE SHOULD BE A DEFINITIVE AND EASILY ACCESSED SOURCE OF TRUTH FOR THIS (also essential for building qa tests). Writing this gets tricky when we consider that we have to account for the fact that a query could be run on arbitrary cohorts, so any contextual assumptions should also be clearly stated.
2. We could improve the metadata that is displayed for various fields. At a glance, users will need to know if a groupby is made based on data physically present in the patient record or an NLP-derived or other complex logical result that they could then lookup in our docs/etc.

I think we could defer technical lift here and consider this a process request

**Comment by dogversioning** [comment]
@James-R-Jones is it fair to say this issue is covered by our training mateirals or is this still an issue

**Comment by dogversioning** [comment]
Closing as covered by training materials
