### ISSUE TITLE
QA/Verify "system" standard referenced by each EHR for Encounter 

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#82]
USCDIv1 = STU4 = http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-encounter.html

**CLASS** (http://hl7.org/fhir/R4/encounter-definitions.html#Encounter.classHistory.class)
http://terminology.hl7.org/ValueSet/v3-ActEncounterCode
http://terminology.hl7.org/CodeSystem/v3-ActCode
http://terminology.hl7.org/CodeSystem/v2-0004
2.16.840.1.113883.1.11.13955

**TYPE** (http://hl7.org/fhir/R4/encounter-definitions.html#Encounter.type)
http://hl7.org/fhir/ValueSet/encounter-type
http://terminology.hl7.org/CodeSystem/encounter-type
http://terminology.hl7.org/CodeSystem/v2-0004
2.16.840.1.113883.4.642.3.248

**SERVICE** (https://hl7.org/fhir/R4/encounter-definitions.html#Encounter.serviceType)
http://hl7.org/fhir/ValueSet/service-type
http://terminology.hl7.org/CodeSystem/service-type
2.16.840.1.113883.4.642.3.518

**PRIORITY** (https://hl7.org/fhir/R4/encounter-definitions.html#Encounter.priority)
http://terminology.hl7.org/ValueSet/v3-ActPriority
http://terminology.hl7.org/CodeSystem/v3-ActPriority

**Comment by dogversioning** [comment]
This is now addressable via the `discovery` study, though we need to get folks to run this.

**Comment by dogversioning** [comment]
resolved by #178 and the [symptom extractor](https://github.com/smart-on-fhir/cumulus-system-extractor)
