### ISSUE TITLE
core__count_condition_month Display is always "None"

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#95]
cond_code_display is always "None" 

source: UCDavis Epic

**Comment by comorbidity** [comment]
Note that Epic is using an unlisted system Namespace
urn:oid:**1.2.840.114350.1.13.93.2.7.2.768282**

Even HL7 doesn't have the entry 
https://www.hl7.org/oid/

Only the root is known as "epic"
http://oidref.com/1.2.840.114350

![image](https://github.com/smart-on-fhir/cumulus-library/assets/96439283/a939d323-b21e-4261-87e8-b48d910246cf)

**Comment by dogversioning** [comment]
This is addressed via #178 and the [symptom extractor](https://github.com/smart-on-fhir/cumulus-system-extractor)
