### ISSUE TITLE
VSAC ValueSet: Medication Clinical Drug

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library#99]
This is the standard medication list , general to any study, as is required per USCDI (STU4) 
http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-medicationrequest.html

https://vsac.nlm.nih.gov/valueset/2.16.840.1.113762.1.4.1010.4/expansion

`OID = 2.16.840.1.113762.1.4.1010.4`

**Comment by dogversioning** [comment]
An API for downloading from VSAC has been added as part of #223

**Comment by dogversioning** [comment]
closing this as we've used this method of lookup in several places now.
